spring:
  application:
    name: orderservice
  data:
    mongodb:
      uri: "mongodb://root:root@localhost:27017/order_db?authSource=admin"

server:
  port: 8082

  eureka:
    instance:
      hostname: orderservice
    client:
      register-with-eureka: true
      fetch-registry: true
      serviceUrl:
        defaultZone: http://orderservice:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"