spring:
  application:
    name: orderservice
  data:
    mongodb:
      uri: "mongodb://root:root@orderservice_db:27017/order_db?authSource=admin"

  kafka:
    bootstrapServer: "localhost:9092"
    template:
      default-topic: orderTopic
    producer:
      keySerializer: org.apache.kafka.common.serialization.StringSerializer
      valueSerializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8082

eureka:
  url: http://orderservice:8888
  instance:
    hostname: eureka
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
